8349944: [JMH] sun.misc.UnsafeOps cannot access class jdk.internal.misc.Unsafe
The UnsafeOps JMH benchmark fails with the following error:

      ```
      java.lang.IllegalAccessError: class org.openjdk.bench.sun.misc.UnsafeOps (in unnamed module @0x520a3426) cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @0x520a3426
      ```

To resolve this, we add the required `--add-opens` flag to grant access
for the benchmark.

Change-Id: I30de213daa9160ee872a4364eb332dcd1636a9ac