fix: report error when cannot find exception name
Doclint does this already:

  error: reference not found
       * @throws X {@inheritDoc}
         ^

Not sure how to coordinate doclint with the other diagnostic system
so that they work in a mutually exclusive fashion and not double
report.