BootClassPathZip64Test: Do not attempt to delete the ZIP file
Leave deletion to the test harness instead, to avoid this on
windows-x64:

command: main -Xbootclasspath/a:./Zip64.zip BootClassPathZip64Test
reason: User specified action: run main/othervm -Xbootclasspath/a:./Zip64.zip BootClassPathZip64Test
started: Tue Jul 02 22:10:56 UTC 2024
Mode: othervm [/othervm specified]
finished: Tue Jul 02 22:10:56 UTC 2024
elapsed time (seconds): 0.265
configuration:
STDOUT:
STDERR:
java.nio.file.FileSystemException: Zip64.zip: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:273)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1192)
	at BootClassPathZip64Creator.tearDown(BootClassPathZip64Creator.java:342)
	at BootClassPathZip64Test.main(BootClassPathZip64Test.java:57)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:1575)