Rework JPackageCommand#withToolProvider() to run workload in a new native thread instead of a virtual thread from a pool. Pooled and/or virtual threads are problematic when used with inheritable thread-local variables. TKit class depends on such a variable, which results in intermittent test failure:
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "jdk.jpackage.test.TestInstance.workDir()" because the return value of "jdk.jpackage.test.TKit.currentTest()" is null
	at java.base/java.util.concurrent.CompletableFuture.wrapInCompletionException(CompletableFuture.java:323)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:359)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:364)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1828)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1817)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1436)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2011)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.lang.NullPointerException: Cannot invoke "jdk.jpackage.test.TestInstance.workDir()" because the return value of "jdk.jpackage.test.TKit.currentTest()" is null
	at jdk.jpackage.test.TKit.workDir(TKit.java:244)
	at jdk.jpackage.test.JPackageCommand.setDefaultInputOutput(JPackageCommand.java:280)
	at jdk.jpackage.test.JPackageCommand.helloAppImage(JPackageCommand.java:384)
	at jdk.jpackage.test.JPackageCommand.helloAppImage(JPackageCommand.java:361)
	at jdk.jpackage/jdk.jpackage.internal.cli.MainTest.lambda$testFailedCommandOutput$2(MainTest.java:123)
	at jdk.jpackage.test.JPackageCommand.lambda$withToolProvider$0(JPackageCommand.java:805)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1825)
	... 5 more