8296656: java.lang.NoClassDefFoundError exception on running fully legitimate code 8287885: Local classes cause ClassLoader error if the type names are similar but not same
Reviewed-by: vromero