8344697: avoid state.set(Animating.YES) for default buttons
I tried removing PULSED entirely, but then the default button didn't get its special background color. So instead I renamed it to DEFAULTBUTTON, and it rendered as expected again.

I tried renaming `_pulsed` to `_defaultbutton`, but JRSUIConstantSync.m compiles with an error no matter what I tried. This is probably a simple problem, but I'm not familiar with .m files.

If I try to rename the _pulsed constant to _defaultbutton, then `make` command fails with:

```
Building target 'default (exploded-image)' in configuration 'macosx-aarch64-server-release'
Updating support/modules_libs/java.desktop/libosxui.dylib due to 1 file(s)
/Users/jeremy/IdeaProjects/jdk/src/java.desktop/macosx/native/libosxui/JRSUIConstantSync.m:214:5: error: use of undeclared identifier 'kJRSUI_State_defaultbutton'
  214 |     CONSISTENCY_CHECK(State, defaultbutton);
      |     ^
/Users/jeremy/IdeaProjects/jdk/src/java.desktop/macosx/native/libosxui/JRSUIConstantSync.m:96:11: note: expanded from macro 'CONSISTENCY_CHECK'
   96 |     if ( !CONSTANT_CHECK(clazz, constant) ) return NO;
      |           ^
/Users/jeremy/IdeaProjects/jdk/src/java.desktop/macosx/native/libosxui/JRSUIConstantSync.m:93:7: note: expanded from macro 'CONSTANT_CHECK'
   93 |     ( JRS_CONSTANT(clazz, constant) == JNI_CONSTANT(clazz, constant) )
      |       ^
/Users/jeremy/IdeaProjects/jdk/src/java.desktop/macosx/native/libosxui/JRSUIConstantSync.m:87:5: note: expanded from macro 'JRS_CONSTANT'
   87 |     kJRSUI_ ## clazz ## _ ## constant
      |     ^
<scratch space>:139:1: note: expanded from here
  139 | kJRSUI_State_defaultbutton
      | ^
1 error generated.
make[3]: *** [/Users/jeremy/IdeaProjects/jdk/build/macosx-aarch64-server-release/support/native/java.desktop/libosxui/JRSUIConstantSync.o] Error 1
make[2]: *** [java.desktop-libs] Error 2

ERROR: Build failed for target 'default (exploded-image)' in configuration 'macosx-aarch64-server-release' (exit code 2)
```