src: hotspot: share: gc: shenandoah: fix constexpr
Older GCC versions (e.g., GCC 6.x from bootlin toolchains) enforce
C++14 rules more strictly and do not allow constexpr member functions
on non-literal types. ShenandoahSimpleBitMap is not a literal type
because it has a non-trivial destructor or other disqualifying members.

Remove constexpr from ShenandoahSimpleBitMap::alignment() to fix the
build with older toolchains. The function can still be inlined and
optimized.

Fixes:

  /home/thomas/br-test-pkg/bootlin-aarch64-glibc-old/build/openjdk-25.0.2+10/src/hotspot/share/gc/shenandoah/shenandoahSimpleBitMap.hpp:93:26: error: enclosing class of constexpr non-static member function 'idx_t ShenandoahSimpleBitMap::alignment() const' is not a literal type
     inline constexpr idx_t alignment() const {
                            ^~~~~~~~~

Signed-off-by: Thomas Devoogdt <thomas@devoogdt.com>