8133625: src/share/vm/opto/compile.hpp:96: error: integer constant is too large for ‘long’ type
Wrap constant causing the failure into into CONST64(). Update comments.

Reviewed-by: kvn