8176501: Method Shape.getBounds2D() incorrectly includes Bezier control points in bounding box
Adding missing @param tag.

This is in response to prrace's code review feedback:

> For me it doesn't build because of a doclint error

> src/java.desktop/share/classes/java/awt/geom/Path2D.java:2102:
> warning: no @param for pi
> public static Rectangle2D getBounds2D(final PathIterator pi) {
> ^
> error: warnings found and -Werror specified

https://github.com/openjdk/jdk/pull/6227#issuecomment-995305817