refactor: do not use "stringly typed" exceptions
Comparing exceptions by their string names is incorrect.
This commit makes ThrowsTaglet "javax.lang.model typed"
rather than "stringly typed".

Changing the comparison mechanism broke 2 tests, which were
subsequently fixed by removing problematic @throws/@exception tag.
In neither test exceptions were pertinent:

* testHtmlDefinitionListTag used `@exception HeadlessException` to test
  HTML structure of `<dl>` tags generated by javadoc (see 6786690).
  For whatever reason, the exception was unknown. It's possible that
  it was supposed to be java.awt.HeadlessException, but it was neither
  imported nor FQNed in the tag. Since a particular type of exception
  does not matter in that test, this PR FQNed that exception.

* TestStdDoclet used `@throws DoesNotExist` as one of the warnings to
  contribute to the total warning count. Interestingly enough, the
  unknown exception in `@throws` was never warned about, unlike
  unknown references in 2 `@see` tags. This PR substitutes that
  exception with a separate test. Note that if "-Xdoclint:none"
  is removed, then that @throws tag triggers a doclint error:

      error: reference not found

To test and support the comparison mechanism change, many new tests
were introduced. They clearly show why being "stringly typed" is wrong
for ThrowsTaglet.